image: "ubuntu:latest"

before_script:
  - RUN apt-get install -y locales locales-all
  - ENV LC_ALL en_US.UTF-8
  - ENV LANG en_US.UTF-8
  - ENV LANGUAGE en_US.UTF-8
  - apt update
  - apt install -y python3 python3-pip openjdk-8-jdk 
  - python3 --version
  - pip3 install -r requirements.txt --upgrade
  - java -jar antlr-4.7.2-complete.jar -Dlanguage=Python3 -visitor TaskLexer.g4 TaskParser.g4

stages:
  - test
  
test:
  stage: test
  script:
    - python3 TaskLanguage.py --test
  tags:
    - asprunner

