image: python:latest

before_script:
  - apt update
  - python -V
  - pip install -r requirements.txt --upgrade
  - cd src/
  - java -jar antlr-4.7.2-complete.jar -Dlanguage=Python3 -visitor TaskLexer.g4 TaskParser.g4

stages:
  - test
  
test:
  stage: test
  script:
    - export PYTHONIOENCODING=utf-8
    - python TaskLanguageTest.py
  tags:
    - asprunner