site_name: LoTLan
site_description: LoTLan
docs_dir: docs/
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: true 
theme:
    name: readthedocs

nav:    
    - Home: index.md
    - Installation: install.md
    - API:
        - Materialflow: api/materialflow.md
        - TransportOrder: api/transportorder.md
        - TransportOrderStep: api/transportorderstep.md
        - Location: api/location.md
        - Event: api/event.md
    - Tutorials:
        - CLI: tutorials/cli.md